services:
  - type: web
    name: novrintech-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_URL
        value: https://api.groq.com/openai/v1/chat/completions
      - key: BACKEND_URL
        value: https://novrintech-ai-backend.onrender.com